# Dependabot configuration for automated dependency updates
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
#
# Philosophy: Fail fast on security. Auto-merge patches and security updates.
# Major versions are manual to avoid breaking changes.

version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"  # Check daily for security patches
      day: "monday"
    open-pull-requests-limit: 10
    # Ignore major version bumps (breaking changes need manual review)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "alexg-g"
    labels:
      - "dependabot"
    # Group non-security updates to reduce PR noise
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy*"
        update-types:
          - "minor"
          - "patch"

  # Frontend dependencies (Next.js)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"  # Check daily for security
      day: "monday"
    open-pull-requests-limit: 10
    # Ignore major version bumps (breaking changes need manual review)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "alexg-g"
    labels:
      - "dependabot"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "next"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"

  # MCP Filesystem Server
  - package-ecosystem: "npm"
    directory: "/mcp-servers/filesystem"
    schedule:
      interval: "daily"
      day: "monday"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "alexg-g"
    labels:
      - "dependabot"

  # MCP GitHub Server
  - package-ecosystem: "npm"
    directory: "/mcp-servers/github"
    schedule:
      interval: "daily"
      day: "monday"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "alexg-g"
    labels:
      - "dependabot"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "alexg-g"
    labels:
      - "dependabot"

  # GitHub Actions workflows (if any)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "alexg-g"
    labels:
      - "dependabot"
