name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-backend:
    name: Security Audit - Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip>=25.3 setuptools>=78.1.1

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run pip-audit security scan
        run: |
          cd backend
          pip install pip-audit
          pip-audit --desc
        continue-on-error: false

  security-frontend:
    name: Security Audit - Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run npm audit
        run: |
          cd frontend
          npm audit --audit-level=high
        continue-on-error: false

  security-mcp-servers:
    name: Security Audit - MCP Servers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Audit Filesystem Server
        run: |
          cd mcp-servers/filesystem
          npm install
          npm audit --audit-level=high
        continue-on-error: false

      - name: Audit GitHub Server
        run: |
          cd mcp-servers/github
          npm install
          npm audit --audit-level=high
        continue-on-error: false

  build-backend:
    name: Build Check - Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip>=25.3 setuptools>=78.1.1

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Check Python syntax
        run: |
          cd backend
          python -m py_compile main.py
          python -m py_compile agents/*.py
          python -m py_compile models/*.py
          python -m py_compile routers/*.py

  build-frontend:
    name: Build Check - Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000

  status-check:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [security-backend, security-frontend, security-mcp-servers, build-backend, build-frontend]
    if: always()

    steps:
      - name: Check all jobs
        run: |
          if [ "${{ needs.security-backend.result }}" != "success" ] || \
             [ "${{ needs.security-frontend.result }}" != "success" ] || \
             [ "${{ needs.security-mcp-servers.result }}" != "success" ] || \
             [ "${{ needs.build-backend.result }}" != "success" ] || \
             [ "${{ needs.build-frontend.result }}" != "success" ]; then
            echo "One or more checks failed"
            exit 1
          fi
          echo "✅ All checks passed!"
